package com.workhub.projectNotification.entity;

public enum NotificationType {
    REVIEW_REQUEST,
    REVIEW_COMPLETED,
    REVIEW_REJECTED,
    STATUS_CHANGED,
    POST_CREATED,
    POST_UPDATED,
    POST_DELETED,
    POST_COMMENT_CREATED,
    CS_QNA_CREATED,
    CS_QNA_ANSWERED,
    CS_POST_CREATED,
    CS_POST_UPDATED,
    CS_QNA_COMMENT_CREATED
}
