package com.workhub.projectNotification.entity;

public enum NotificationType {
    REVIEW_REQUEST,
    REVIEW_COMPLETED,
    REVIEW_REJECTED,
    STATUS_CHANGED,
    PROJECT_CREATED,
    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_REMOVED,
    PROJECT_INFO_UPDATED,
    PROJECT_NODE_CREATED,
    PROJECT_NODE_UPDATED,
    POST_CREATED,
    POST_UPDATED,
    POST_COMMENT_CREATED,
    CS_QNA_CREATED,
    CS_QNA_ANSWERED,
    CS_POST_CREATED,
    CS_POST_UPDATED,
    CHECKLIST_CREATED,
    CHECKLIST_UPDATED,
    CHECKLIST_ITEM_STATUS_CHANGED,
    CHECKLIST_COMMENT_CREATED
}
